@startuml
start
:開始;
if(分岐条件)then (yes)
:最初の条件を実行;
:そのあとの実行;
elseif (条件分岐2) then (yes)
:次の条件を実施;
else (それ以外)
:それ以外の処理;
endif

:ループ;

while (条件が成立している間)
:永久ループの実行;
endwhile
:終了;
end
@enduml

@startuml
title 直角を挟む2辺を入力して斜辺を計算するプログラム
start
:開始;
:変数宣言;
:斜辺の長さを保存する変数宣言(z変数);
:xの長さ入力;
:yの長さを入力;
:x * xを行い　x変数に代入し2乗;
:y * yを行い2乗 y変数に代入し2乗;
if (x + yを行う) then (計算が可能)
:x + yで計算した数値をz変数に代入;
:斜辺の長さをプリントアウトする;
end
else (計算ができない)
:エラー文を出し入力手順に戻す;
end
@enduml